### ISSUE TITLE
Allow user to choose HTTP over HTTPS, or handle and allow user to ignore unsigned SSL cert issue

### ISSUE THREAD

**Issue by tm-robinson** [kmansoft/clearview-android#1]
Trying to use this on a local internal network where clearview-server is running behind nginx which only has a self-signed certificate available.  The android app fails to connect as the certificate is not trusted, and there is no way for the user to ignore this and continue.  It would be good if the option to select HTTP was given, or the user was given an option to ignore the SSL issues (if this is possible).  Looks like there is already some code to handle this if the app is built with debug more on?  https://github.com/kmansoft/clearview-android/blob/1dfc4d8f1bb9e1e05b52a4d3eca23fd35ab00f43/src/main/java/org/kman/clearview/core/BaseViewModel.kt#L33

**Comment by kmansoft** [comment]
Added in the just published app version 0.1.4-11.

It will take 1-2 days for Google to review and clear the update.

Meanwhile, feel free to update from here: https://clearview.rocks/download/clearview-0.1.4-11.apk

**Comment by tm-robinson** [comment]
Thanks, this definitely helps!  Unfortunately as I am trying to specify port 81 (which Nginx is running on) I get "unexpected host: 192.168.1.189:81" when connecting.

If I switch it to run on port 80, it connects but I get Login Error.  I'm specifying the username and password from `clearview-server.conf` which work for me when connecting using the Web UI, however from looking at the Nginx access log it seems like they're not being passed through by the app when trying to connect to the API:

`192.168.1.185 - - [23/Jan/2022:10:10:26 +0000] "POST /cv/api/v1/index HTTP/1.1" 401 0 "-" "okhttp/4.10.0-RC1"`

If that was working properly the second `-` should be replaced by the HTTP basic auth username which in my case is `clearview` as can be seen in a successful entry in the Nginx access log when connecting from my desktop machine:

`192.168.1.187 - clearview [23/Jan/2022:01:00:16 +0000] "GET /cv/web/ HTTP/1.1" 200 5357 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15"`

I worked around this issue as well by adding a line temporarily to my Nginx configuration to pass through the HTTP basic auth username and password to the clearview server on behalf of the client:

```
        location /cv/ {
            proxy_pass http://127.0.0.1:63001;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization "Basic base_64_string_removed";
        }
```

Having got this far, the android app does now connect and show me the first `servers` screen with the pie chart, however all the other screens render as a blank page.  You can scroll it up and down but it's just entirely white with no graphs.  The accesses generated by the app do appear in the Nginx access log with 200 responses, so that part seems to be working, but the rendering isn't for some reason.  In my Nginx access log I can see:

```
192.168.1.185 - - [23/Jan/2022:11:15:48 +0000] "POST /cv/api/v1/index HTTP/1.1" 200 261 "-" "okhttp/4.10.0-RC1"
192.168.1.185 - - [23/Jan/2022:11:15:48 +0000] "POST /cv/api/v1/index HTTP/1.1" 200 261 "-" "okhttp/4.10.0-RC1"
192.168.1.185 - - [23/Jan/2022:11:15:56 +0000] "POST /cv/api/v1/get HTTP/1.1" 200 2863 "-" "okhttp/4.10.0-RC1"
192.168.1.185 - - [23/Jan/2022:11:16:05 +0000] "POST /cv/api/v1/get HTTP/1.1" 200 1200 "-" "okhttp/4.10.0-RC1"
192.168.1.185 - - [23/Jan/2022:11:16:07 +0000] "POST /cv/api/v1/get HTTP/1.1" 200 754 "-" "okhttp/4.10.0-RC1"
192.168.1.185 - - [23/Jan/2022:11:16:13 +0000] "POST /cv/api/v1/get HTTP/1.1" 200 754 "-" "okhttp/4.10.0-RC1"
192.168.1.185 - - [23/Jan/2022:11:16:22 +0000] "POST /cv/api/v1/disk_overview HTTP/1.1" 200 442 "-" "okhttp/4.10.0-RC1"
192.168.1.185 - - [23/Jan/2022:11:16:25 +0000] "POST /cv/api/v1/index HTTP/1.1" 200 261 "-" "okhttp/4.10.0-RC1"
```

I'm using a OnePlus Nord CE 5G with Android 11 in case that helps.  

See screenshots:

![WhatsApp Image 2022-01-23 at 11 17 03 AM](https://user-images.githubusercontent.com/13947678/150675863-0de3da13-500b-43bc-8720-038f540f22b4.jpeg)
![WhatsApp Image 2022-01-23 at 11 16 56 AM](https://user-images.githubusercontent.com/13947678/150675865-a50f808d-18a2-4b46-be1a-354e52a397d3.jpeg)
![WhatsApp Image 2022-01-23 at 11 16 48 AM](https://user-images.githubusercontent.com/13947678/150675866-e1a56ff6-c955-4de1-97d4-255eb42e028d.jpeg)

**Comment by kmansoft** [comment]
I'll check out these issues with a nginx reverse proxy.

Regarding auth, the app definitely generates an auth header, but maybe it's getting stripped by OkHttp, I'll have to check that.

It's been two years + since I wrote the app, bit rot I guess :)

**Comment by kmansoft** [comment]
Found several issues, here come the fixes.

1 - Please update the server and agent to 0.2.0-7

Since you're using plain http, please edit `/etc/clearview.conf` for the agent and set `insecure = true`. This should fix the "no data" issue, the agent uses https by default and was not able to send data to the server.

If there is still no data, please check `journalctl -f -u clearview-agent`.

2 - For nginx proxying, you also need `proxy_pass_header Authorization` in the `location` block:

```
        location /cv/ {
            proxy_pass http://127.0.0.1:63001;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass_header Authorization;
        }
``` 

I've updated the instructions on the web site.

3 - Please update Android app to 0.1.4-12, should be available on Play in a day or two, or use this:

https://clearview.rocks/download/clearview-0.1.4-12.apk

The server name can now be entered as `server:port` where `:port` is optional.

I also fixed the auth header.

**Comment by tm-robinson** [comment]
Awesome!! That is all working beautifully now, including the app! :) Thank you so much for the quick fixes.

**Comment by kmansoft** [comment]
Great, glad to hear it!
